#  A single Neuron

In [1]:

# # modeling a single neuron with 3 inputs

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2 # 1 bias value per neuron, tunable value not associated with  any input

output = (inputs[0]*weights[0] +
          inputs[1]*weights[1] +
          inputs[2]*weights[2] + 
          inputs[3]*weights[3] + bias)
print(output)


4.8


# A layer of Neurons


In [1]:
inputs = [1.0, 2.0, 3.0, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
        # Neuron 1:
          inputs[0]*weights1[0] +
          inputs[1]*weights1[1] +
          inputs[2]*weights1[2] + 
          inputs[3]*weights1[3] + bias1,
          
        # Neuron 2:
          inputs[0]*weights2[0] +
          inputs[1]*weights2[1] +
          inputs[2]*weights2[2] + 
          inputs[3]*weights2[3] + bias2,
          
        # Neuron 3:
          inputs[0]*weights3[0] +
          inputs[1]*weights3[1] +
          inputs[2]*weights3[2] + 
          inputs[3]*weights3[3] + bias3]

print(outputs)


[4.8, 1.21, 2.385]


In [2]:
#  Loop to scale and and handle dynamically-sized inputs and layers

inputs = [1.0, 2.0, 3.0, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]


# output of current layer
layer_outputs = []

# For each neuron(3), 3 elements inside the weights list, and 3 biases...
for neuron_weights, neuron_bias in zip(weights, biases):
    # initialize Neuron output to zero
    neuron_output = 0
    # ...for each of neuron take each element from each set of weights of the weights list and each input from the input list
    for n_input, weight in zip(inputs, neuron_weights):
        # multiply input by associated weight
        # & add them all under neuron's output variable
        neuron_output += n_input*weight
    # add bias ONCE
    neuron_output += neuron_bias
    # Put neuron's result to the layer's output list
    layer_outputs.append(neuron_output)
    
print(layer_outputs)
        

[4.8, 1.21, 2.385]


# Tensors, Arrays and Vectors 



Indices refer to how many numbers are required to access an element of the ndTensor

Indexes required	Computer science	Mathematics
     0              number	            scalar
     1              array	            vector
     2              2d-array	        matrix


A scalar is a 0 dimensional tensor
A vector is a 1 dimensional tensor
A matrix is a 2 dimensional tensor
A nd-array is an n dimensional tensor   

In [2]:
# Simple List

l = [1, 5, 6, 2]


# Lists of lists

lol = [[1, 5, 6, 2],
       [3, 2, 1, 3]]


# Lists of lists

lolol = [ 
          [[1, 5, 6, 2],
          [3, 2, 1, 3]],
        
         [[1, 5, 6, 2],
          [3, 2, 1, 3]],
          
          [[1, 5, 6, 2],
          [3, 2, 1, 3]] 
                        ]


# Dot Product and Vector Addition

a⋅b=a1b1+a2b2

In [3]:
a= [1, 2, 3]
b= [2, 3, 4]

dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2] 
print(dot_product)


20


# A Single Nueron with NumPy



In [4]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

outputs = np.dot(weights, inputs) + bias

print(outputs)

4.8


# A Layer of Neurons with NumPy



In [5]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(weights, inputs) + biases

print(layer_outputs)

[4.8   1.21  2.385]


# A Batch of Data

untill now we have been using input data which is only one sample/observation of various features called a feature set

inputs = [1, 2, 3, 2.5] 
shape : (4, )
type : 1D, Vector

together they form a feature set instance, also called an observation, or most commonly known as a sample

often nueral networks expect to take in many samples at a time for 2 reasons:
1. faster to train in batches in parallel processing 
2. batches help with generalization during training

example of batch data : 

inputs = [[0, 2, 3, 2.5],
          [1, 0, 3, 2.5],
          [1, 2, 0, 2.5],
          [1, 2, 3, 0]] 
shape : (4, 4)
type : 2D Array, Matrix

# Matrix Product

lists of lists can be made into arrays if homolofous, but they would contain now multiple batches of training data(rows)


    

In [7]:
# a = [1 2 3]

# b = [2]
#     [3]
#     [4]
#             [2]
# ab = [1 2 3][3] = [20]
#             [4]

 row and column vectors are matrices with one of their dimensions being of a size
of 1; and, we perform the matrix product on them instead of the dot product, which results in
a matrix containing a single value. In this case, we performed a matrix multiplication of matrices
with shapes (1, 3) and (3, 1), then the resulting array has the shape (1, 1) or a size of 1x1.

# Transposition for the Matrix Product

Transpostion modifies a matrix in a way that its rows become columns and columns become rows

A row vector is a matrix whos first dimension's (rows) size=1 and the second dimension's size(columns)=n. i.e 1xn array or array of shape (1, n)

In [8]:
np.array([[1, 2, 3]])

array([[1, 2, 3]])

In [9]:
a = [1, 2, 3]
print(np.array([a]))

[[1 2 3]]


In [12]:
# equivilent

a = [1, 2, 3]
print(np.expand_dims(np.array(a), axis=0))

[[1 2 3]]


    Everytime we are transforming a list into matrix by adding a new dimension at the idex of the axis

A column vector is a matrix where the second dimension's size(columns)=n. i.e nx1 array or array of shape (n, 1)

before calculating the dot product, the matrix b in a*b must be :
1. turned into a row vecotr(increase the dimension)
2. Transpose b from a row vector into a column vector


In [13]:
import numpy as np

a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T

print(np.dot(a, b))


[[20]]


To perform a matrix product on two vectors, we took one as is, transforming it into
a row vector, and the second one using transposition on it to turn it into a column vector. That
allowed us to perform a matrix product that returned a matrix containing a single value. We also
performed the matrix product on two example arrays to learn how a matrix product works — it
creates a matrix of dot products of all combinations of row and column vectors.

# A Layer of Neurons & Batch of Data with NumPy

In [14]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

The Matrix product takes all the of the combinations of rows from the left matrix and columns from the right matrixm performing the dot product on them and placing the results in an output array. In order to perform the matrix product the shape's value from the index 1 (columns) of the first matrix and the index 0 (rows) of the second matrix must match.
They dont right now

In [19]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(inputs, np.array(weights).T) + biases

print(layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


    The output is a list of predictions